import { useMemo, useState } from 'react'
import { BookOpen, CircleHelp, Gauge, ListTree } from 'lucide-react'
import { commandReference } from '../../data/linux/labContent'
import type { LinuxLabSession } from '../../lib/linuxTerminal'
import { FileTree } from './FileTree'

type ToolTab='files'|'help'|'commands'|'status'
export function LabToolPanel({session,onInsert}:{session:LinuxLabSession;onInsert:(value:string)=>void}){
  const [tab,setTab]=useState<ToolTab>('files');const [selected,setSelected]=useState('pwd')
  const tabs:[ToolTab,string,typeof ListTree][]=[['files','Dateien',ListTree],['help','Hilfe',CircleHelp],['commands','Befehle',BookOpen],['status','Status',Gauge]]
  const reference=useMemo(()=>commandReference.find(item=>item.command===selected)??commandReference[0],[selected])
  return <aside className="min-w-0" aria-label="Linux-Lab-Werkzeuge">
    <div className="mb-3 grid grid-cols-4 rounded-lg bg-ink-100 p-1 dark:bg-ink-900">{tabs.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} aria-pressed={tab===id} className={`flex min-h-10 items-center justify-center gap-1 rounded-md px-2 text-xs font-semibold ${tab===id?'bg-white text-brand-700 shadow-sm dark:bg-ink-800 dark:text-brand-300':'text-ink-500 dark:text-ink-400'}`}><Icon className="h-3.5 w-3.5"/><span className="hidden 2xl:inline">{label}</span></button>)}</div>
    {tab==='files'&&<FileTree session={session}/>}
    {tab==='help'&&<section className="rounded-xl border border-ink-200 bg-white p-4 dark:border-ink-800 dark:bg-ink-900"><h2 className="font-semibold text-ink-950 dark:text-white">Sicher üben</h2><div className="mt-3 space-y-3 text-sm leading-6 text-ink-600 dark:text-ink-300"><p>Diese Umgebung ist vollständig simuliert. Du kannst nichts auf deinem Computer beschädigen.</p><p><strong>Tab</strong> vervollständigt Befehle und Pfade. <strong>↑/↓</strong> durchsucht den Verlauf. <strong>Strg+L</strong> leert die Ausgabe. <strong>Strg+C</strong> bricht die aktuelle Eingabe ab.</p><p>Mit <code data-no-translate>help</code> siehst du Befehle, mit <code data-no-translate>man ls</code> eine Kurzhilfe.</p></div></section>}
    {tab==='commands'&&<section className="rounded-xl border border-ink-200 bg-white p-4 dark:border-ink-800 dark:bg-ink-900"><label className="text-xs font-semibold text-ink-500">Befehl auswählen<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-2 h-10 w-full rounded-md border bg-white px-2 font-mono text-sm dark:bg-ink-950">{commandReference.map(item=><option key={item.command}>{item.command}</option>)}</select></label><div className="mt-4 text-sm"><h2 className="font-mono text-lg font-bold text-brand-700 dark:text-brand-300">{reference.command}</h2><p className="mt-1 text-ink-600 dark:text-ink-300">{reference.purpose}</p><p className="mt-4 text-xs font-semibold uppercase text-ink-400">Syntax</p><code className="mt-1 block rounded-md bg-ink-950 p-2 text-xs text-white" data-no-translate>{reference.syntax}</code><p className="mt-3 text-xs font-semibold uppercase text-ink-400">Beispiel</p><code className="mt-1 block rounded-md bg-ink-950 p-2 text-xs text-white" data-no-translate>{reference.example}</code><button type="button" onClick={()=>onInsert(reference.example)} className="mt-4 min-h-10 rounded-md border px-3 text-xs font-semibold text-brand-700 hover:bg-brand-50 dark:text-brand-300 dark:hover:bg-brand-500/10">In Terminal einfügen</button></div></section>}
    {tab==='status'&&<section className="rounded-xl border border-ink-200 bg-white p-4 dark:border-ink-800 dark:bg-ink-900"><h2 className="font-semibold text-ink-950 dark:text-white">Systemstatus</h2><dl className="mt-4 space-y-2 text-sm">{Object.entries(session.services).map(([name,state])=><div key={name} className="flex justify-between"><dt className="font-mono">{name}</dt><dd className={state==='running'?'text-emerald-600':'text-amber-600'}>{state}</dd></div>)}<div className="flex justify-between border-t pt-2"><dt>Prozesse</dt><dd>{session.processes.length}</dd></div><div className="flex justify-between"><dt>Git</dt><dd>{session.git.initialized?'aktiv':'inaktiv'}</dd></div></dl></section>}
  </aside>
}

