import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { CheckCircle2, ChevronDown, Circle, Expand, FlaskConical, Focus, ListChecks, RotateCcw, TerminalSquare } from 'lucide-react'
import { Button } from '../components/Button'
import { LabTaskPanel } from '../components/linuxLab/LabTaskPanel'
import { LabToolPanel } from '../components/linuxLab/LabToolPanel'
import { TerminalConsole, type TerminalEntry } from '../components/linuxLab/TerminalConsole'
import { useLearningProgress } from '../contexts/LearningProgressContext'
import { linuxScenarios } from '../data/linux/labContent'
import { terminalExercises } from '../data/linux/terminalExercises'
import { createLinuxLabSession, runLinuxCommand, type LinuxLabSession } from '../lib/linuxTerminal'
import { LabReturnLink } from '../components/labs/LabReturnLink'

type LabMode='guided'|'free'|'scenarios'
const progressId=(id:string)=>`linux-lab-${id}`
const modeLabel:Record<LabMode,string>={guided:'Guided Lab',free:'Freies Terminal',scenarios:'Szenarien'}

export default function LinuxTerminalTrainer(){
 const [params,setParams]=useSearchParams(); const requestedMode=params.get('mode') as LabMode|null
 const [mode,setMode]=useState<LabMode>(requestedMode&&['guided','free','scenarios'].includes(requestedMode)?requestedMode:'guided')
 const initialChallenge=Math.max(0,terminalExercises.findIndex(item=>item.id===params.get('challenge')||item.lessonSlug===params.get('lesson')))
 const initialScenario=Math.max(0,linuxScenarios.findIndex(item=>item.id===params.get('scenario')))
 const initialSession=()=>requestedMode==='scenarios'?linuxScenarios[initialScenario].prepare(createLinuxLabSession()):createLinuxLabSession()
 const [activeIndex,setActiveIndex]=useState(initialChallenge);const [scenarioIndex,setScenarioIndex]=useState(initialScenario)
 const [session,setSession]=useState<LinuxLabSession>(initialSession);const [snapshot,setSnapshot]=useState<LinuxLabSession>(()=>structuredClone(initialSession()))
 const [entries,setEntries]=useState<TerminalEntry[]>([]);const [command,setCommand]=useState('');const [historyIndex,setHistoryIndex]=useState(-1)
 const [hintLevel,setHintLevel]=useState(0);const [focusMode,setFocusMode]=useState(false);const [listOpen,setListOpen]=useState(false)
 const [attempts,setAttempts]=useState(0);const [commandsAtStart,setCommandsAtStart]=useState(0);const [lastOutput,setLastOutput]=useState('')
 const [sessionSuccesses,setSessionSuccesses]=useState<Set<string>>(new Set());const [hintsUsed,setHintsUsed]=useState(0)
 const {isCompleted,isPending,toggleCompleted}=useLearningProgress();const completionInFlight=useRef<Set<string>>(new Set())
 const activeChallenge=terminalExercises[activeIndex];const activeScenario=linuxScenarios[scenarioIndex]
 const done=mode==='guided'?(isCompleted(progressId(activeChallenge.id))||sessionSuccesses.has(activeChallenge.id)):mode==='scenarios'?activeScenario.isComplete(session):false
 const completedCount=useMemo(()=>terminalExercises.filter(item=>isCompleted(progressId(item.id))||sessionSuccesses.has(item.id)).length,[isCompleted,sessionSuccesses])
 const percent=Math.round(completedCount/terminalExercises.length*100);const commandCount=session.commandHistory.length
 useEffect(()=>{if(!focusMode)return;const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setFocusMode(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[focusMode])
 useEffect(()=>{if(mode!=='guided'||!activeChallenge.isComplete(session,lastOutput))return;setSessionSuccesses(current=>current.has(activeChallenge.id)?current:new Set(current).add(activeChallenge.id));const id=progressId(activeChallenge.id);if(isCompleted(id)||isPending(id)||completionInFlight.current.has(id))return;completionInFlight.current.add(id);void toggleCompleted(id).finally(()=>completionInFlight.current.delete(id))},[activeChallenge,isCompleted,isPending,lastOutput,mode,session,toggleCompleted])
 function execute(){if(!command.trim())return;const promptPath=session.cwd.replace('/home/student','~')||'~';const evaluation=runLinuxCommand(session,command);setSession(evaluation.session);setLastOutput(evaluation.output);setEntries(current=>evaluation.clear?[]:[...current,{id:Date.now(),prompt:`${session.user}@${session.hostname}:${promptPath}`,command:command.trim(),output:evaluation.output,error:evaluation.error}]);if(evaluation.error)setAttempts(value=>value+1);setCommand('');setHistoryIndex(-1)}
 const source=params.get('source')
 const withSource=(values:Record<string,string>)=>source?{...values,source}:values
 function activateMode(next:LabMode){setMode(next);setParams(withSource(next==='guided'?{}:{mode:next}));setFocusMode(false);setHintLevel(0);if(next==='scenarios')loadScenario(scenarioIndex)}
 function loadChallenge(index:number){setActiveIndex(index);setParams(withSource({challenge:terminalExercises[index].id}));setHintLevel(0);setAttempts(0);setCommandsAtStart(session.commandHistory.length);setSnapshot(structuredClone(session));setListOpen(false)}
 function loadScenario(index:number){const base=createLinuxLabSession();const prepared=linuxScenarios[index].prepare(base);setScenarioIndex(index);setSession(prepared);setSnapshot(structuredClone(prepared));setEntries([]);setHintLevel(0);setAttempts(0);setCommandsAtStart(0);setLastOutput('');setParams(withSource({mode:'scenarios',scenario:linuxScenarios[index].id}));setListOpen(false)}
 function resetCurrent(){setSession(structuredClone(snapshot));setEntries([]);setCommand('');setLastOutput('');setAttempts(0);setHistoryIndex(-1)}
 function resetAll(){if(!window.confirm('Gesamte simulierte Umgebung zurücksetzen? Dein gespeicherter Lernfortschritt bleibt erhalten.'))return;const fresh=createLinuxLabSession();setSession(fresh);setSnapshot(structuredClone(fresh));setEntries([]);setCommand('');setLastOutput('');setAttempts(0);setHistoryIndex(-1)}
 const activeItem=mode==='scenarios'?activeScenario:activeChallenge
 const next=()=>mode==='guided'?loadChallenge((activeIndex+1)%terminalExercises.length):loadScenario((scenarioIndex+1)%linuxScenarios.length)
 const welcome=mode==='free'?'Willkommen im FISI Linux Lab.\nDiese Umgebung ist vollständig simuliert.\nMit "help" siehst du verfügbare Befehle.':mode==='scenarios'?`Szenario: ${activeScenario.title}\nUntersuche das System und behebe die Ursache.`:'FISI Linux Lab — Guided Practice\nArbeite auf das Ziel hin; valide Lösungen werden am Systemzustand erkannt.'
 return <main className={`mx-auto w-full px-4 py-6 sm:px-6 lg:px-8 ${focusMode?'max-w-none':'max-w-[100rem]'}`}>
  {!focusMode&&<><LabReturnLink/><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-sm text-ink-500 dark:text-ink-400"><Link to="/it">IT</Link><span>/</span><Link to="/it/linux">Linux</Link><span>/</span><span>Linux Lab</span></nav>
  <header className="mt-4 flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-brand-700 dark:text-brand-300"><FlaskConical className="h-4 w-4"/> Sichere praktische Lernumgebung</div><h1 className="mt-2 text-3xl font-bold tracking-tight text-ink-950 dark:text-white">Linux Lab</h1><p className="mt-2 leading-6 text-ink-600 dark:text-ink-300">Lerne im geführten Kurs, experimentiere frei oder löse realistische Administrationsfälle – vollständig simuliert im Browser.</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" icon={<Focus/>} onClick={()=>setFocusMode(true)}>Fokusmodus</Button><Button variant="secondary" size="sm" icon={<RotateCcw/>} onClick={resetAll}>Umgebung zurücksetzen</Button></div></header>
  <div className="mt-5 flex flex-col gap-4 rounded-xl border border-ink-200 bg-white p-3 dark:border-ink-800 dark:bg-ink-900 lg:flex-row lg:items-center lg:justify-between"><div className="grid grid-cols-3 rounded-lg bg-ink-100 p-1 dark:bg-ink-950" role="tablist" aria-label="Linux-Lab-Modus">{(['guided','free','scenarios'] as LabMode[]).map(item=><button key={item} role="tab" aria-selected={mode===item} onClick={()=>activateMode(item)} className={`min-h-10 rounded-md px-3 text-xs font-semibold sm:text-sm ${mode===item?'bg-white text-brand-700 shadow-sm dark:bg-ink-800 dark:text-brand-300':'text-ink-500 dark:text-ink-400'}`}>{modeLabel[item]}</button>)}</div><div className="flex items-center gap-4 text-xs text-ink-500"><span>{commandCount} Befehle</span><span>{hintsUsed} Tipps</span><span>{completedCount}/{terminalExercises.length} Aufgaben</span></div>{mode==='guided'&&<div className="min-w-48"><div className="flex justify-between text-xs"><span>Fortschritt</span><span>{percent}%</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-ink-100 dark:bg-ink-800"><div className="h-full bg-brand-600" style={{width:`${percent}%`}}/></div></div>}</div></>}
  {focusMode&&<div className="mb-3 flex items-center justify-between rounded-lg border bg-white px-3 py-2 dark:bg-ink-900"><div className="min-w-0"><span className="text-xs font-semibold text-brand-600">{modeLabel[mode]}</span><p className="truncate text-sm font-semibold">{mode==='free'?'Freies Üben':activeItem.title}</p></div><Button size="sm" variant="secondary" icon={<Expand/>} onClick={()=>setFocusMode(false)}>Fokus verlassen</Button></div>}
  {!focusMode&&mode!=='free'&&<div className="mt-4 lg:hidden"><button type="button" onClick={()=>setListOpen(value=>!value)} className="flex min-h-11 w-full items-center justify-between rounded-lg border bg-white px-3 text-sm font-semibold dark:bg-ink-900"><span className="flex items-center gap-2"><ListChecks className="h-4 w-4"/> {activeItem.title}</span><ChevronDown className={`h-4 w-4 ${listOpen?'rotate-180':''}`}/></button></div>}
  <div className={`mt-4 grid min-w-0 gap-4 ${focusMode?'grid-cols-1':mode==='free'?'2xl:grid-cols-[minmax(0,1fr)_19rem]':'lg:grid-cols-[17rem_minmax(0,1fr)] 2xl:grid-cols-[18rem_minmax(0,1fr)_19rem]'}`}>
   {!focusMode&&mode!=='free'&&<aside className={`${listOpen?'block':'hidden'} min-w-0 lg:block`}><div className="space-y-4 lg:sticky lg:top-20"><LabTaskPanel item={activeItem} kind={mode==='guided'?'challenge':'scenario'} done={done} hintLevel={hintLevel} attempts={attempts} commands={session.commandHistory.slice(commandsAtStart)} onHint={()=>{setHintLevel(value=>value+1);setHintsUsed(value=>value+1)}} onInsert={setCommand} onNext={next} onRetry={resetCurrent}/><div className="max-h-72 overflow-auto rounded-xl border bg-white p-2 dark:bg-ink-900">{(mode==='guided'?terminalExercises:linuxScenarios).map((item,index)=>{const selected=index===(mode==='guided'?activeIndex:scenarioIndex);const complete=mode==='guided'?(isCompleted(progressId(item.id))||sessionSuccesses.has(item.id)):linuxScenarios[index].isComplete(session);return <button key={item.id} onClick={()=>mode==='guided'?loadChallenge(index):loadScenario(index)} className={`flex min-h-10 w-full items-center gap-2 rounded-md px-2 text-left text-xs ${selected?'bg-brand-50 font-semibold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300':'text-ink-600 hover:bg-ink-50 dark:text-ink-300 dark:hover:bg-ink-800'}`}>{complete?<CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500"/>:<Circle className="h-4 w-4 shrink-0 text-ink-300"/>}<span className="truncate">{item.title}</span></button>})}</div></div></aside>}
   <div className="min-w-0"><TerminalConsole session={session} entries={entries} command={command} historyIndex={historyIndex} onCommandChange={setCommand} onHistoryIndexChange={setHistoryIndex} onSubmit={execute} onReset={resetCurrent} onClear={()=>setEntries([])} focusMode={focusMode} welcome={welcome}/>{!focusMode&&mode==='free'&&<div className="mt-3 rounded-lg border border-brand-200 bg-brand-50 p-3 text-sm text-brand-800 dark:border-brand-500/20 dark:bg-brand-500/5 dark:text-brand-200"><TerminalSquare className="mr-2 inline h-4 w-4"/>Freies Terminal: keine Aufgabenbewertung, kein Risiko. Setze die Umgebung jederzeit zurück.</div>}</div>
   {!focusMode&&<div className={mode==='free'?'2xl:block':'lg:col-start-2 2xl:col-start-auto'}><LabToolPanel session={session} onInsert={setCommand}/></div>}
  </div>
 </main>
}
